apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sgx8r4u67-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sgx8r4u67-dotnet-basic 
  name: sgx8r4u67-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sgx8r4u67-dotnet-basic 
